<%
  platforms = %w(centos-7 centos-6)
  use_git = true
  use_json = true
%>
---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  sudo: true
  sudo_options: '-u root'
  inspec_tests:
    - name: nginix-baseline
      git: https://github.com/aaronlippold/nginx-baseline.git
    - name: disa_stig-el7
      git: https://github.com/jburns12/inspec-profile-disa_stig-el7.git
  <% if use_json == true %>
  format: json
  output: "%{platform}_%{suite}-<%= Time.now.iso8601 %>.json"
  <% end %>

platforms:
<% platforms.each do |plat| %>
- name: <%= plat %>
<% end %>

suites:
  - name: hardened-nginx
    run_list:
      - recipe[auditd]
      - recipe[stig::auditd]
      - recipe[stig::auditd_rules]
      - recipe[stig::fstab_tmp]
      - recipe[stig::tcp_wrappers]
      - recipe[stig::boot_settings]
      - recipe[stig::proc_hard]
      - recipe[stig::cis]
      - recipe[stig::avahi_daemon]
      - recipe[stig::ipv6]
      - recipe[stig::dhcp]
      - recipe[stig::mail_transfer_agent]
      - recipe[stig::hosts]
      - recipe[stig::rsyslog]
      - recipe[logrotate::global]
      - recipe[stig::sshd_config]
      - recipe[stig::system_auth]
      - recipe[stig::login_defs]
      - recipe[stig::login_banner]
      - recipe[stig::file_permissions]
      - recipe[stig::audits]
      - recipe[stig::audit_scripts]
      - recipe[stig::su_restriction]
      - recipe[stig::aide]

      # nginx runlist
      - recipe[apt]
      - recipe[nginx-hardening::upgrades]
      - recipe[chef_nginx]
      - recipe[nginx-hardening]

    attributes:
      "auditd" :
        "ruleset" : "stig"

  - name: vanilla-nginx
    run_list:
      - recipe[apt]
      - recipe[nginx-hardening::upgrades]
      - recipe[chef_nginx]
